### PR TITLE
Improve CMake Setup So CMake Users Can Easily Consume Library

### PR DESCRIPTION
**Pull request by ptsouchlos**
## Added

* Library target for `easy-socket`. This name can be changed
* Version of library in project declaration
* All needed config files and install rules so distribution is easy for CMake users
  * This will make it easy to make this library available on `vcpkg` or something similar. 
* Option to turn off building of client/server tests so consumers aren't forced to build these projects. 

## Fixed
* Windows build using CMake was broken. It was necessary to link to `wsock32` and `ws2_32`. 

**Notes:**
* I only tested the Windows build. Not sure what is/could be broken on Linux.

### CODE REVIEW

**Comment by masesk** [comment]
Looks good to me!
I will test the Linux version on Monday and report back any issues, if any.
Thank you!

**Comment by ptsouchlos** [comment]
@masesk I was able to test building my changes on WSL via Visual Studio using Clang and GCC and everything built fine, just an FYI 👍

**Comment by masesk** [comment]
Everything seems to work correctly aside from the following:
`make install ` seems to output to
`/usr/local/include-0.2.0/include/masesk/EasySocket.hpp`

I believe this is due to line 54-57, where the include install puts it in the word include and version. 
On Linux, this should be `/usr/local/include/masesk/EasySocket.hpp`

Also, I couldn't find any reason why we store the `easy-socketTargets.cmake`, `easy-socketConfigVersion.cmake`, and `easy-socketConfig.cmake`. I have no experience in this matter so any information would be helpful :)

**Comment by ptsouchlos** [comment]
Yes I see that now you're right, that's the wrong include path. That should be a simple fix

> Also, I couldn't find any reason why we store the easy-socketTargets.cmake, easy-socketConfigVersion.cmake, and easy-socketConfig.cmake. I have no experience in this matter so any information would be helpful :)

These files are used by consumers of the library (assuming they are using CMake). So in a consumer's `CMakeLists.txt`, they going to require a dependency on your lib

`find_package(easy-socket REQUIRED)`

By default, CMake has a number of paths that it uses to search to find `easy-socket`. It's going to first try to find a [Find Module](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) and when it can't, it will look for a config file. All config files have to be named `<library name>Config.cmake`. So providing these files will make it easy to integrate your library into their project. Once the location of the `easy-socketConfig.cmake` file is specified they can just link to your project in one line:

`target_link_libraries(MyProject PUBLIC easy-socket)`

Hopefully that made sense; let me know if there are further questions.

**Comment by ptsouchlos** [comment]
I was able to fix the include directory install location.

**Comment by masesk** [comment]
Awesome work!
Similarly, I think the installation paths for all the config files are:
`/usr/local/lib/cmake/easy-socket-0.2.0/easy-socket/easy-socketConfig.cmake`
`/usr/local/lib/cmake/easy-socket-0.2.0/easy-socket/easy-socketTargets.cmake`
`/usr/local/lib/cmake/easy-socket-0.2.0/easy-socket/easy-socketConfigVersion.cmake`
I think the `easy-socket-0.2.0` should not be there. Otherwise the `find_package(easy-socket REQUIRED)` won't find it. Correct me if I am wrong.

**Comment by ptsouchlos** [comment]
That is there on purpose to support side by side installation of multiple versions. If you don't think it's needed I can remove it.

**Pull request merged**
